force-app/main/default/objects/Accounts__c/Accounts__c.object-meta.xml
<CustomObject>
    <label>Accounts</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Accounts__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The category of financial account (e.g. Bank Account, Credit Card, Cash, Wallet, Investment, Other).</description>
    <inlineHelpText>Select the type that best describes this account.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Account</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Wallet</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Object is used to record expenses</description>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Accounts__c.field-meta.xml
<CustomField>
    <fullName>Accounts__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Accounts</label>
    <referenceTo>Accounts__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Debit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Debit_Amount__c</fullName>
    <label>Debit Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Debited_On__c.field-meta.xml
<CustomField>
    <fullName>Debited_On__c</fullName>
    <description>Date when the amount is debited</description>
    <inlineHelpText>Select when the amount is debited</inlineHelpText>
    <label>Debited On</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Recurring_Payment__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Payment</label>
    <referenceTo>Recurring_Payment__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Payment__c/Recurring_Payment__c.object-meta.xml
<CustomObject>
    <label>Recurring Payment</label>
    <nameField>
        <label>Recurring Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recurring_Payment__c/fields/Accounts__c.field-meta.xml
<CustomField>
    <fullName>Accounts__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Accounts</label>
    <referenceTo>Accounts__c</referenceTo>
    <relationshipLabel>Recurring Payments</relationshipLabel>
    <relationshipName>Recurring_Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurring_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Subscription Amount</description>
    <inlineHelpText>Enter the subscription cost.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recurring_Payment__c/fields/Auto_Create_Expense__c.field-meta.xml
<CustomField>
    <fullName>Auto_Create_Expense__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Create Expense</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recurring_Payment__c/fields/Billing_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Billing_Cycle__c</fullName>
    <label>Billing Cycle</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Quaterly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>9 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Payment__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Payment__c/fields/Last_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Billing_Date__c</fullName>
    <label>Last Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recurring_Payment__c/fields/Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Date__c</fullName>
    <label>Next Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recurring_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Payment__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Activities / Sightseeing</fullName>
    </customValue>
    <customValue>
        <fullName>Auto / Rickshaw</fullName>
    </customValue>
    <customValue>
        <fullName>Bank Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Books</fullName>
    </customValue>
    <customValue>
        <fullName>Cab / Taxi</fullName>
    </customValue>
    <customValue>
        <fullName>Cafes / Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>Certifications</fullName>
    </customValue>
    <customValue>
        <fullName>Clothes</fullName>
    </customValue>
    <customValue>
        <fullName>Courses</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card Bill</fullName>
    </customValue>
    <customValue>
        <fullName>Dating / Outings</fullName>
    </customValue>
    <customValue>
        <fullName>Dining Out</fullName>
    </customValue>
    <customValue>
        <fullName>Doctor Visits</fullName>
    </customValue>
    <customValue>
        <fullName>DTH / TV</fullName>
    </customValue>
    <customValue>
        <fullName>Electricity</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>EMI</fullName>
    </customValue>
    <customValue>
        <fullName>Events / Concerts</fullName>
    </customValue>
    <customValue>
        <fullName>Flights</fullName>
    </customValue>
    <customValue>
        <fullName>Food Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Food during Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Fuel</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts</fullName>
    </customValue>
    <customValue>
        <fullName>Groceries</fullName>
    </customValue>
    <customValue>
        <fullName>Grooming / Salon</fullName>
    </customValue>
    <customValue>
        <fullName>Gym Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Health Checkups</fullName>
    </customValue>
    <masterLabel>Sub Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bills &amp; Utilities</fullName>
    </customValue>
    <customValue>
        <fullName>Education</fullName>
    </customValue>
    <customValue>
        <fullName>Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Financial</fullName>
    </customValue>
    <customValue>
        <fullName>Food &amp; Dining</fullName>
    </customValue>
    <customValue>
        <fullName>Health &amp; Fitness</fullName>
    </customValue>
    <customValue>
        <fullName>Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>Personal &amp; Lifestyle</fullName>
    </customValue>
    <customValue>
        <fullName>Shopping</fullName>
    </customValue>
    <customValue>
        <fullName>Transport</fullName>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Fund Transfer</fullName>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RecurringPaymentScheduler.cls
public with sharing class RecurringPaymentScheduler Implements Schedulable {
    public void execute(SchedulableContext sc){
        try {
            Date TodaysDate = System.today();
            List<Recurring_Payment__c> recurringPayments = [SELECT Id, Name, Category__c, Sub_Category__c, Amount__c, Billing_Cycle__c, Next_Billing_Date__c, Accounts__c, Last_Billing_Date__c, Status__c, Auto_Create_Expense__c
                                                            FROM Recurring_Payment__c
                                                            WHERE Status__c = 'Active'
                                                            AND Auto_Create_Expense__c = TRUE
                                                            AND Next_Billing_Date__c = :TodaysDate
                                                           ];
            List<Expense__c> expenseToCreate = new List<Expense__c>();
            List<Recurring_Payment__c> PaymentToUpdate = new List<Recurring_Payment__c>();
            for(Recurring_Payment__c recurringPayment : recurringPayments){
                if(recurringPayment.Next_Billing_Date__c == TodaysDate && recurringPayment.Last_Billing_Date__c >= TodaysDate){
                    Boolean dateAdvanced = true;
                    switch on recurringPayment.Billing_Cycle__c{
                        when 'Monthly' {
                            recurringPayment.Next_Billing_Date__c = recurringPayment.Next_Billing_Date__c.addMonths(1);
                        }
                        when 'Yearly' {
                            recurringPayment.Next_Billing_Date__c = recurringPayment.Next_Billing_Date__c.addYears(1);
                        }
                        when 'Quaterly' {
                            recurringPayment.Next_Billing_Date__c = recurringPayment.Next_Billing_Date__c.addMonths(3);
                        }
                        when 'Half Yearly' {
                            recurringPayment.Next_Billing_Date__c = recurringPayment.Next_Billing_Date__c.addMonths(6);
                        }
                        when '9 Months' {
                            recurringPayment.Next_Billing_Date__c = recurringPayment.Next_Billing_Date__c.addMonths(9);
                        }
                        when else {
                            dateAdvanced = false;
                        }
                    }
                    if(dateAdvanced) {
                        expenseToCreate.add(new Expense__c(
                            Name = recurringPayment.Name,
                            Debited_On__c = TodaysDate,
                            Type__c = recurringPayment.Category__c,
                            Sub_Type__c = recurringPayment.Sub_Category__c,
                            Debit_Amount__c = recurringPayment.Amount__c,
                            Accounts__c = recurringPayment.Accounts__c,
                            Recurring_Payment__c = recurringPayment.Id
                        ));
                        if(recurringPayment.Next_Billing_Date__c >= recurringPayment.Last_Billing_Date__c) {
                            recurringPayment.Status__c = 'Completed';
                            recurringPayment.Auto_Create_Expense__c = false;
                        }
                        PaymentToUpdate.add(recurringPayment);
                    }
                }
            }
            if(!expenseToCreate.isEmpty()) {
                insert expenseToCreate;
            }
            if(!PaymentToUpdate.isEmpty()) {
                update PaymentToUpdate;
            }
        } catch(Exception e) {
            System.debug(LoggingLevel.ERROR, 'RecurringPaymentScheduler failed: ' + e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

}